version: '2'
services:
  docproxy:
    build: ./docproxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/cert:/cert
    environment:
      - SERVER
      - SANS
    networks:
      - reverseproxy

networks:
  reverseproxy:
    driver: bridge
